### ISSUE TITLE
Cannot find ReportPortal.conf file osx

### ISSUE THREAD

**Issue by nabsofken** [reportportal/agent-net-nunit#10]
I installed docker and ran Report portal successfully. I also installed the report portal nuget package successfully and manually placed the reportportal.conf file in the correct location. But I get the following error:
`System.IO.FileNotFoundException: Could not find file "/Users/HelloWorld_iPhone/UITests/bin/iPhoneSimulator/Auto\ReportPortal.conf` seems like the backslash is causing the issue. Is there a way to modify it to be a forwardslash instead as I am using a mac?

**Comment by nvborisenko** [comment]
Fix is available in 3.2.3-beta-3
Please verify

**Comment by nabsofken** [comment]
@nvborisenko thanks!! fix works in 3.2.3-beta-3. Closing
