### ISSUE TITLE
How to setup jenkins runs

### ISSUE THREAD

**Issue by nabsofken** [reportportal/agent-net-nunit#11]
I want to set different launch names e.g smoke test run, regression run from the nunit 3 command line instead of the ReportPortal.conf file. Is this possible? The wesbite shows how to do it with mvn but I would like to know how to do it with nunit.

**Comment by nvborisenko** [comment]
Currently there is no way to put launch name as environment variable. But there is possibility to change the data in real-time. Please see [example](https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.csl) how to do it. Please reply here is this works for you.

**Comment by nabsofken** [comment]
@nvborisenko I cant access the example page.

**Comment by nabsofken** [comment]
I have tests written in specflow but I was running them using nunit. I don't think I can use the Extension class for nunit. I will try with the specflow extension now that RP works with specflow 2.2
