### ISSUE TITLE
Extension fails if test name is longer than 256 characters

### ISSUE THREAD

**Issue by Andrey-Cherepakha** [reportportal/agent-net-nunit#12]
ReportPortal.Client 1.2.9
ReportPortal.Nunit 3.2.2
ReportPortal.Shared 1.4.2

**Comment by nvborisenko** [comment]
ReportPortal.Client 1.2.9 automatically trims the names. Cannot reproduce.

**Comment by Andrey-Cherepakha** [comment]
Looks like ReportPortal.Client 1.2.3 was cached for some reason. Cannot reproduce with ReportPortal.Client 1.2.9
