### ISSUE TITLE
Messages from logger frameworks come to console

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/agent-net-nunit#15]
All messages from loggers should be hidden

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko assign you to fix? :)

**Comment by nvborisenko** [comment]
Could be fixed on nunit side: https://github.com/nunit/nunit-console/issues/433

**Comment by nvborisenko** [comment]
As a temporary workaround `--output` parameter can be applied to nunit-console.
```cmd
nunit-console.exe ....... --output:console.txt
```
All console output from tests will be written to `console.txt` file.

**Comment by nvborisenko** [comment]
This issue will be resolved when https://github.com/nunit/nunit/pull/3018 will be merged. It seems we are in awaiting NUnit 3.11

**Comment by nvborisenko** [comment]
Fixed in v3.4.0
