### ISSUE TITLE
NuGet package contains incorrect path to ReportPortal.conf file

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/agent-net-nunit#17]
We need remove this file from package. User will add it manually.

**Comment by fjody** [comment]
![image](https://user-images.githubusercontent.com/4049697/44857136-76d7c680-ac6f-11e8-969d-5184f8e565f2.png)
When I would like to delete it in Visual Studio, it doesn't want to allow me.
_(issue was told to Mikalai)_

**Comment by nvborisenko** [comment]
The issue is reproducible only for `PackageReference` projects, this is new csproj format. Nuget adds `ReportPortal.conf` file into project by global cache path. It's not bad, user still is able to edit file, but these changes are per user machine. Not acceptable for us.
There are 2 ways to resolve it:
- Officially wait when this issue will be resolved on NuGet side: https://github.com/NuGet/Home/issues/5963
- Apply "workaround" to resolve it on our side. Good news are there is working example how to do it.

Cannot make a decision yet which way is better, let's wait more impacted users.

**Comment by nvborisenko** [comment]
Decided to remove this file from package. User should manually add it to a test project. We will provide a json schema. In future we can provide additional package to install config file.

**Comment by nvborisenko** [comment]
Fixed in v3.4.0
