### ISSUE TITLE
Ignoring attachment body during serialization to console output only

### ISSUE THREAD

**Issue by tazik047** [reportportal/agent-net-nunit#19]
Using `Bridge.LogMessage()` with attachment serialize useless large binary array with attachment to console output (Jenkins, ReSharper test output and etc).
I hopped that pull request #18 may fix this problem but as I understand `ReportPortal.NUnitExtension.Attach` class is used for sending to RP too.
So, how attachment data can be skipped for console output only?

**Comment by nvborisenko** [comment]
There is another issue when all internal messages in nunit comes to console.
https://github.com/reportportal/agent-net-nunit/issues/15
Closing this one as duplicate.
