### ISSUE TITLE
Console.WriteLine texts are in Report Portal test case report

### ISSUE THREAD

**Issue by fjody** [reportportal/agent-net-nunit#20]
When I use this code:
```
_stackTrace = new StackTrace();
_methodBase = _stackTrace.GetFrame(1).GetMethod();
String messageHead = getNowDateTime() + " CP " + _methodBase.ReflectedType.Name + " : " + _methodBase.Name + " - ";
Console.WriteLine(messageHead + message);
Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Debug, messageHead + message + "{rp#file#" + filePath + "}");

```
then the test execution will write the Console.WriteLine texts into ReportPortal, unfortunately.
See: attached pics
![issue_testoutput-in-rp](https://user-images.githubusercontent.com/4049697/45088993-03203880-b10b-11e8-8db7-5f3df6ffb589.png)

**Comment by nvborisenko** [comment]
Added new `BeforeTestOutput` event in **v3.3.7**. You can subscribe on this event and set `e.Canceled` to `true`. It means the agent will not send test output to the server.

**Comment by fjody** [comment]
Thanks for your help guys.
It was solved. I created my own customization as in the example.
See:
```
public ReportPortalCustomization() {
       ReportPortal.NUnitExtension.ReportPortalListener.BeforeTestOutput += ReportPortalListener_BeforeTestOutput;
}
```
```
// Won't write the Test Output section to Report Portal.
private void ReportPortalListener_BeforeTestOutput(object sender, ReportPortal.NUnitExtension.EventArguments.TestItemOutputEventArgs e)
	{
		e.Canceled = true;
	}
```

After that I only have to execute the test.
nice job, and thank you again @MikalaiB for your help through chat .
