### ISSUE TITLE
Incorrect RP NUnit dll for multiple test projects

### ISSUE THREAD

**Issue by damianpereira86** [reportportal/agent-net-nunit#38]
I have a solution with several test projects, each one of them has it's own ReportPortal.NUnitExtension.dll and it's own ReportPortal.config. 

I added a ReportPortal.addins file to the NUnitConsole folder to show Nunit the location of the RP extension. It looks like this:
../Solution/TestProject1/bin/Debug/ReportPortal.NUnitExtension.dll
../Solution/TestProject2/bin/Debug/ReportPortal.NUnitExtension.dll

If I run the tests for TestProject1 the correct Launch is created (taken from TestProject1 config):
nunit3-console ..\TestProject1\bin\Debug\TestProject1.dll

However, if I run the tests for TestProject2, the tests are run correctly, but the Launch name is the one in the TestProject1 config file.

Probably the reason is that NUnit uses the first ReportPortal.NUnitExtension.dll that it finds in the .addins file(../Solution/TestProject1/bin/Debug/ReportPortal.NUnitExtension.dll) therefore using the config file for TestProject1.

I'm not totally sure I'm doing the right steps. I would like to have a different Launch name for every Test project. Is there any way to accomplish this? Please let me know if you need more info on this.

**Comment by nvborisenko** [comment]
Seems so, runner uses only the first adding from your Project1 folder.
I recommend to override configuration parameters via environment variables: https://github.com/reportportal/agent-net-nunit#environment-variables

```bash
set reportportal_launch_name="My name for Project1"
# execute Project1

set reportportal_launch_name="My name for Project2"
# execute Project2
```

**Comment by nvborisenko** [comment]
@damianpereira86 by default nunit creates single xml report. I think it's possible to make the behavior of agent configurable: create separate launches per test assembly or not. But again, only 1 config file can be used by agent due nunit uses one instance of addin.

Generally it would be resolved on nunit side. Currently nunit doesn't support addins per test assembly.
