### ISSUE TITLE
VS 2019 16.2.3 no longer logs with nunit

### ISSUE THREAD

**Issue by staind825** [reportportal/agent-net-nunit#44]
I updated my Visual studio 2019 to 16.2.3 and i no longer see ReportPortal results. My enterprise VS instance is still an older version and it works. Also a coworker of mine hasn't update VS 2019 and it still works for them in the same project.

**Comment by nvborisenko** [comment]
The same for me. Microsoft always is changing the behavior, not sure what will be tomorrow. If time will allow I will investigate how to make `NUnit3TestAdapter` smarter and minimize the influence of Visual Studio.

**Comment by nvborisenko** [comment]
The following workaround works for me:
- Create new `runsettings` file somewhere, example - https://github.com/reportportal/example-net-nunit/blob/develop/src/ReportPortal.runsettings
- Choose this file in VS Test Explorer (three dots -> Settings -> Configure Run Settings -> Select file) 

Execute test in VS Test Explorer and see result on RP.

Seems this workaround forces Visual Studio to load extensions for your tests output folder what we have expected before.

Please try and report whether it works for you.

**Comment by eddie101AMR** [comment]
I added .runsettings file to the main folder of the project, load it in VS Test Explorer (three dots -> Settings -> Configure Run Settings -> Select file)
but it didn't work.
should I change the "." in TestAdaptersPaths  to specific path ?
<TestAdaptersPaths>.</TestAdaptersPaths>

**Comment by nvborisenko** [comment]
Please try to specify the full path o the directory.

**Comment by eddie101AMR** [comment]
changed it to ..\ and it worked : ), thanks
I have more than one project in the solution, 
I think that was the problem,
I'll wait for charlie to fix TestCentric from his side, I still need a standalone test runner that work with ReportPortal
I'm trying to find a workaround with no luck.

**Comment by eddie101AMR** [comment]
Hi @nvborisenko ,
I just updated MSTest.TestAdapter from 1.3.2 to 2.1.1 , MSTest.TestFramework from 1.3.2 to 2.1.1 and Nunit from 3.11 to 3.12,
NUnit.ConsolrRunner and TestCentric is still working and reporting to ReportPortal but VS test explorer stop reporting to ReportPortal, 
did Microsoft changed thing again ?
