### ISSUE TITLE
Can I enable ReportPortal grammatically in code?

### ISSUE THREAD

**Issue by Lemm1** [reportportal/agent-net-nunit#52]
Do ReportPortal have ability to enable it in code? I don't want to change json every time when I need it and it's easier for me to handle it in code.

**Comment by nvborisenko** [comment]
Does setting properties via environment variables suite your needs?
Or you really want to use c# code to set it? And which properties from json you want to override?

**Comment by Lemm1** [comment]
>  And which properties from json you want to override?
"enabled": false
> Does setting properties via environment variables suite your needs?
If it overrides "enabled":false in ReportPortal.config.json it would be great.

**Comment by Lemm1** [comment]
Seems that I can understand what are you proposing. If I set environment variable `reportportal_enabled=true` it will override my `"enabled":false"` in ReportPortal.config.json.
Thanks, for your help.

**Comment by nvborisenko** [comment]
Right, some docs https://github.com/reportportal/agent-net-nunit#environment-variables
Closing issue, feel free to reopen in case of any questions.
