### ISSUE TITLE
ReportPortal.config.json modification on runtime 

### ISSUE THREAD

**Issue by eddie101AMR** [reportportal/agent-net-nunit#60]
Hi, 
I need to modify and change some of ReportPortal.config.json parameters ("project",  "name" etc) on test runtime,

"$schema": "https://raw.githubusercontent.com/reportportal/agent-net-nunit/master/ReportPortal.NUnitExtension/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "url": "http://10.0.0.0:8080/api/v1/",
    **"project"**: "OMD",
    "authentication": {
      "uuid": "e58b2d23-4b64-43bb-aff0-67ceb2053aca"
    }
  },
  "launch": {
    **"name"**: "Sanity Autorun",
    "description": "Automation",
    "debugMode": false,
    "tags": ["Testing" ]
  },
  "rootNamespaces": [ "Automation.Framework.dll", "Automation", "Tests" ]

what is the best and easy way to do that,
my motivation is that I want to run multiple tests from multiple projects with multiple names and I want them ;to be reported to different project in my ReportPortal under different names.

Thanks
Eddie

**Comment by nvborisenko** [comment]
The easiest way to do it is to override configuration via environment variables: https://github.com/reportportal/commons-net/blob/master/docs/Configuration.md#configuration-source
```
set env var
execute tests
```

BTW this situation leads me to think about per project configuration. Similar request is https://github.com/reportportal/agent-net-nunit/issues/38. The problem is that nunit extension lives globally in runner and tries to find configuration in the folder where runner is located. What if extension also will consider test project folder?.. Seems this is possible to implement, but in this case we need to separate launches per test assembly (1 assembly - 1 RP launch).

**Comment by eddie101AMR** [comment]
for now I can report to one project from every dll, so it's not a showstopper for me,
can you please provide an example of how I change the environment variables for launch "name":

"launch": {
**"name"**: "Sanity Autorun",
"description": "Automation",
"debugMode": false,
"tags": ["Testing" ]

can I run this setting before every test in order to decide what name I want to report for every specific test ?

**Comment by nvborisenko** [comment]
Please visualize actual behavior and what you expect. It's hard to understand what you need :( Also would be nice to represent a way how you execute tests. Thanks.

**Comment by eddie101AMR** [comment]
I'm executing my tests from Nunit console runner and from the new TestCentric, 
everything works as expected, I can see the reports in the ReportPortal that I built,
in my testing project I added ReportPortal.config.json with these default values:

"$schema": "https://raw.githubusercontent.com/reportportal/agent-net-nunit/master/ReportPortal.NUnitExtension/ReportPortal.config.schema",
"enabled": true,
"server": {
"url": "http://10.0.0.0:8080/api/v1/",
"project": "OMD",
"authentication": {
"uuid": "e58b2d23-4b64-43bb-aff0-67ceb2053aca"
}
},
"launch": {
"name": "Sanity Autorun",
"description": "Automation",
"debugMode": false,
"tags": ["Testing" ]
},
"rootNamespaces": [ "Automation.Framework.dll", "Automation", "Tests" ]

now with these values I see that every launch of tests have the same name, in this case it's "Sanity Autorun",
now lets assume that I have 3 classes of tests in the same project and I run every class in a different run of different machine,
in this case I see that the 3 runs (classes) report 3 entries with the same name "Sanity Autorun" and that's okay because they're all in the same project that have the same ReportPortal.config.json,
what I'm trying to do is to add pre test method "[OneTimeSetUp] maybe" to update the launch "name in ReportPortal.config.json in order to report different name for every class that I run.
sorry if I missed it up again and you still didn't understand, please tell me and I'll try to explain again.

Thanks
Eddie

**Comment by nvborisenko** [comment]
> now lets assume that I have 3 classes of tests in the same project and I run every class in a different run of different machine

Just define `reportportal_launch_name` environment variable on the machine where you run tests. The value, you set, will be used as new value for launch name.

**Comment by evjlobanova** [comment]
@eddie101AMR I am a little bit confused, what do you mean under "filter widgets"?

**Comment by eddie101AMR** [comment]
@evjlobanova  lets assume that I'm running 3 test classes in one launch,
I  should see under the launch in reportportal, 3 classes, 
can I add filter to display only one specific class ?
and then I can use that filter to apply it on some widgets.

**Comment by evjlobanova** [comment]
@eddie101AMR you can create filters only for launches.
But we have a widget Component Health Check Widget, it can be applicable for your case.
But you need report your test cases with attributes. 

https://reportportal.io/docs/Component-health-check

**Comment by eddie101AMR** [comment]
mm, I think that I found a way that suits me, 
I need to run pre test configuratior  to config the environment variable,
and just after that to load and execute the test,
but I think that you should consider a feature that give the ability to change launch name on runtime.

thanks for the help 
Eddie
