### ISSUE TITLE
Unable to load shared.IBridgeExtention on version 2.5.0.00 when running through nunit test adapter

### ISSUE THREAD

**Issue by aradyaron** [reportportal/agent-net-nunit#64]

**Comment by nvborisenko** [comment]
Any details?

**Comment by aradyaron** [comment]
Nnitextention=3.7.0
reportportal.client = 2.1.15
reportportal.shared = 2.5.0
![rpt prt error](https://user-images.githubusercontent.com/59508334/89395629-411ea080-d716-11ea-8861-aab8385b8b71.PNG)
please note that the first error was solved by manually importing the nunit.engine 
please note that this works through the nunit-console using this versions

**Comment by nvborisenko** [comment]
Try to upgrade `ReportPortal.NUnit` package to the latest stable `3.7.15`.

**Comment by nvborisenko** [comment]
Considering as solved.
