### ISSUE TITLE
Logs are not reported with NUnit.Engine 12.*

### ISSUE THREAD

**Issue by Bakanych** [reportportal/agent-net-nunit#72]
I've upgraded NUnit packages to the latest versions
```
		<PackageReference Include="NUnit" Version="3.13.1" />
		<PackageReference Include="NUnit.Engine" Version="3.12.0" />
```
Looks like NUnit.Engine 12.* brings some breaking changes which are incompatible with this adapter.

I cannot see any report portal logs reported for the test cases now:
![image](https://user-images.githubusercontent.com/17307409/113092562-cc5a2280-9220-11eb-832c-c7169a109984.png)

**Comment by nvborisenko** [comment]
Also reproducible on my side after directly use the newest version of nunit engine in tests assembly.

https://github.com/reportportal/commons-net/blob/00b25213bbdc1ae487c14af91474d9386a2c928d/src/ReportPortal.Shared/Extensibility/ExtensionManager.cs#L101

This line of code cannot determine that type implements the interface.

**Comment by AngryTester95** [comment]
@Bakanych can you provide a bit more information. I tried to run tests from example projects for integration report portal with NUnit and it works fine with upgrated nuget pacakges:
![image](https://user-images.githubusercontent.com/82048855/116002729-bcf1ad80-a603-11eb-81d5-737846b0a3ca.png)

**Comment by nvborisenko** [comment]
@Bakanych `NUnit.Engine` package is not intended to be referenced from tests assembly. In any case could you please try to reference `NUnit.Engine.Api` package instead of `NUnit.Engine`. At least on my side it works even when `NUnit.Engine.Api` is also not intended to be referenced from tests.

**Comment by Bakanych** [comment]
> @Bakanych `NUnit.Engine` package is not intended to be referenced from tests assembly. In any case could you please try to reference `NUnit.Engine.Api` package instead of `NUnit.Engine`. At least on my side it works even when `NUnit.Engine.Api` is also not intended to be referenced from tests.

I use it for Report portal customizations as described in this example: 
https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

**Comment by Bakanych** [comment]
> @Bakanych `NUnit.Engine` package is not intended to be referenced from tests assembly. In any case could you please try to reference `NUnit.Engine.Api` package instead of `NUnit.Engine`. At least on my side it works even when `NUnit.Engine.Api` is also not intended to be referenced from tests.

Just've tried with
```
		<PackageReference Include="NUnit" Version="3.13.2" />
		<PackageReference Include="NUnit.Engine.Api" Version="3.12.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
		<PackageReference Include="ReportPortal.Extensions.SourceBack" Version="2.0.0" />
		<PackageReference Include="ReportPortal.NUnit" Version="4.0.0" />
```
I cannot see any test runs created in the report portal.

Same bad result with
```
		<PackageReference Include="NUnit" Version="3.13.1" />
		<PackageReference Include="NUnit.Engine.Api" Version="3.11.1" />
```
But if I use 
```
		<PackageReference Include="NUnit" Version="3.13.1" />
		<PackageReference Include="NUnit.Engine" Version="3.11.1" />
```
everything works fine.

I also tried to update NUnit, and looks like it also fails Report portal now. The following combination doesn't work too
```
		<PackageReference Include="NUnit" Version="3.13.2" />
		<PackageReference Include="NUnit.Engine" Version="3.11.1" />
```

**Comment by nvborisenko** [comment]
All combinations of `NUnit` and `NUnit.Engine.Api` work for me. Please share simple project to reproduce the issue without `NUnit.Engine` package.

**Comment by nvborisenko** [comment]
Feel free to reopen it if it's still issue.
