### ISSUE TITLE
RP Listener throws error randomly on StartTest and TestMessage and FinishRun

### ISSUE THREAD

**Issue by bhuptani-neha** [reportportal/agent-net-nunit#83]
Running multiple test cases with nunit and report portal inetgration on ADO.
Getting below errors randomly at different times:
1. ReportPortal exception was thrown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ReportPortal.NUnitExtension.ReportPortalListener.StartTest(XmlDocument xmlDoc)
ReportPortal exception was thrown.

2. ReportPortal exception was thrown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ReportPortal.NUnitExtension.ReportPortalListener.TestMessage(XmlDocument xmlDoc) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Test.cs:line 392
ReportPortal exception was thrown.

3. System.InsufficientExecutionStackException: The launch is already scheduled for finishing.
   at ReportPortal.Shared.Reporter.LaunchReporter.Finish(FinishLaunchRequest request)
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(XmlDocument xmlDoc) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Launch.cs:line 105

Is there any way to debug the cause of these errors and remove them? The respective tests are not getting logged on report portal.

**Comment by nvborisenko** [comment]
Hi @bhuptani-neha 
For the first exception in your list is it full output of this exception? Actually I don't see line number where it was occurred like
> nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Test.cs:line **392**

**Comment by bhuptani-neha** [comment]
> nvborisenko
Hi @nvborisenko  , for the first exception, it is the full output of exception. There is nothing else logged.

**Comment by nvborisenko** [comment]
> Running multiple test cases
When you say multiple, do you mean you execute multiple assemblies in parallel? Please expand your usage of how you execute tests in detail.

**Comment by bhuptani-neha** [comment]
@nvborisenko 
A single test dll is run with test cases having parallel attribute.

**Comment by nvborisenko** [comment]
@bhuptani-neha what version of `ReportPortal.NUnit` package you use?

**Comment by bhuptani-neha** [comment]
@nvborisenko Nunit (3.13.2), Nunit3 Test Adapter (4.2.1) , ReportPortal.NUnit (3.7.13)

**Comment by nvborisenko** [comment]
I suggest upgrading to the latest v 4.3.4

**Comment by bhuptani-neha** [comment]
@nvborisenko  will upgrading version  help for sure? Can you explain me the cause for this error?

**Comment by nvborisenko** [comment]
Not sure, I have no idea what is cause of this issue. On my side parallel tests are reported good.

In any case the potential fix will be evolution of the current latest version.

Would be amazing if you can provide test project to reproduce the issue.

**Comment by nvborisenko** [comment]
BTW Please join [Slack](https://reportportal-slack-auto.herokuapp.com/) and there we can discuss your issue deeply.

**Comment by bhuptani-neha** [comment]
@nvborisenko  Hey I am unable to join the work space

**Comment by bhuptani-neha** [comment]
@nvborisenko  Can you send me the invite as I am not receiving the invite to join the slack for report portal?

**Comment by bhuptani-neha** [comment]
@nvborisenko  There is a certain test I could recognize which gets pass but still its not logged on report portal and gives above provided first error-
ReportPortal exception was thrown.
System.NullReferenceException: Object reference not set to an instance of an object.
at ReportPortal.NUnitExtension.ReportPortalListener.StartTest(XmlDocument xmlDoc)
ReportPortal exception was thrown.

**Comment by nvborisenko** [comment]
Perfect, this is a good catch!

Can you share a definition of this test in code?

Or set `ReportPortal_TraceLevel` env variable to `Verbose` and share `ReportPortal.*.log` files.

**Comment by bhuptani-neha** [comment]
@nvborisenko Where should I set this variable ReportPortal_TraceLevel=Verbose?

**Comment by nvborisenko** [comment]
Nevermind. Please share the signature of test method.

**Comment by bhuptani-neha** [comment]
public void P111111_T222222_Invoice_Paid_viaTPI_ApprovalRouting_AddApprover_Reset(){}

**Comment by bhuptani-neha** [comment]
@nvborisenko is there nay restriction on the length of the test case name for report portal to work properly?

**Comment by nvborisenko** [comment]
Not reproducible on my side

![image](https://user-images.githubusercontent.com/22616990/181504535-2d66c549-54e3-49c6-a88c-3dd48eb6f2ce.png)

Please prepare dummy test project to reproduce the issue, thanks in advance.

**Comment by bhuptani-neha** [comment]
@nvborisenko can you try this? - P141737_T139924_Invoice_Post_viaAPI_ApprovalRouting_ChangeThreshold_Reset
