### ISSUE TITLE
invalid argument: /Logger:ReportPortal

### ISSUE THREAD

**Issue by sjabbal8** [reportportal/agent-net-nunit#85]
Hi
I am unable to upload the results .
![image](https://user-images.githubusercontent.com/113338514/203547388-86670288-095c-4962-8ca0-8b0c3e46ac7f.png)

Can you please help me with it if i am missing something.

**Comment by Aleh-Yanushkevich** [comment]
@sjabbal8 please have a look how to use NUnit console runner + ReportPortal [here](https://github.com/reportportal/agent-net-nunit). As I can see from your screenshot, you are trying to use `/Logger` argument, but this argument is applicable for VS test console, not for NUnit console runner.

**Comment by sjabbal8** [comment]
which command can help me to run the tests is not mentioned in the link

**Comment by Aleh-Yanushkevich** [comment]
@sjabbal8 first of please have a look how to configure your runner for ability to send results to ReportPortal:
![image](https://user-images.githubusercontent.com/103627305/203706734-2a98c244-1d11-4033-9266-363ce81c0285.png)
If you have already done it and your configuration is correct - just run your tests without any extra arguments.

Example of using NUnit with ReportPortal you can find [here](https://github.com/reportportal/example-net-nunit).
